### PR TITLE
CASSANDRA-15229: initiate multiple buffer pool for different lifespan…

### PR DESCRIPTION
**Pull request by jasonstack**
… and usages

* Permanent Pool used by chunk cache or hint reader - conf.file_cache_size_in_mb=512mb
* Ephemeral Pool used by internode/client-server connections - conf.network_cache_size_in_mb=128mb

### CODE REVIEW

**Comment by stef1927** [comment]
Using two separate pools is not sufficient. We also need to remove the fragmentation from the current design for the permanent pool. See this [comment](https://issues.apache.org/jira/browse/CASSANDRA-15229?focusedCommentId=17072895&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17072895) with the details of a possible solution that we've implemented internally (DB-2788). I don't know if this solution would be accepted in OSS so hold on with it.

Using direct allocations when the permanent pool is full is not a good idea IMO. The problem is that we have no control on when the cache will release the memory that it holds. So we could end up with long lived direct allocations and the pool full, which would break the limits set by the users for a very long time.

In terms of testing, I think it's expected that the 20k fixed throughput tests do not show any difference when using direct allocations. I think we need a test with high throughput disk reads, and one that is long lived. I was using the search tests (see DB-2788). Unfortunately they seem to have been deleted in Fallout, and besides they were based on search. We could see if we have an existing haxx test, if not maybe we could use one of the big-node tests. We need to ramp up data, then do something like a 80-20 read-write. I think key-value or tabular would be better than time series, we should read randomly form the entire data set to ensure that we hit the disk and cause churn in the cache.

**Comment by jasonstack** [comment]
I will take a look at DB-2788

> We need to ramp up data, then do something like a 80-20 read-write. I think key-value or tabular would be better than time series, we should read randomly form the entire data set to ensure that we hit the disk and cause churn in the cache.

You are right.. Finally, [kv test: 128mb cache with rampup data and mixed read/write](https://fallout.sjc.dsinternal.org/performance/zhao.yang@datastax.com/report/ef90f5bc-42b2-4a36-95de-27f0b5304945) shows `chunk cache direct allocation` causes higher latency than 15229

**Comment by stef1927** [comment]
> Finally, kv test: 128mb cache with rampup data and mixed read/write shows chunk cache direct allocation causes higher latency than 15229

Well done!

**Comment by jasonstack** [comment]
use https://github.com/apache/cassandra/pull/535 instead

**Pull request closed without merging**
